---
# tasks file for rundeck
- name: Garantir o Java
  yum: name=java 

- name: Download repo
  yum: 
    name: http://repo.rundeck.org/latest.rpm
    state: present

- name: Instalando o Rundeck
  yum: name=rundeck state=present

